<?php
/* Catalan - 200 - https://en.wiktionary.org/wiki/Wiktionary:Frequency_lists/Catalan/1-2000 */
$aWords['ca'] = array ( 'de'            ,   /* 01 */
                        'la'            ,   /* 02 */
                        'i'             ,   /* 03 */
                        'el'            ,   /* 04 */
                        'a'             ,   /* 05 */
                        "l'"            ,   /* 06 */
                        'en'            ,   /* 07 */
                        'que'           ,   /* 08 */
                        "d'"            ,   /* 09 */
                        'va'            ,   /* 10 */
                        'del'           ,   /* 11 */
                        'per'           ,   /* 12 */
                        'les'           ,   /* 13 */
                        'els'           ,   /* 14 */
                        'un'            ,   /* 15 */
                        'amb'           ,   /* 16 */
                        'es'            ,   /* 17 */
                        'al'            ,   /* 18 */
                        'una'           ,   /* 19 */
                        'és'            ,   /* 20 */
                        'com'           ,   /* 21 */
                        'dels'          ,   /* 22 */
                        'més'           ,   /* 23 */
                        'ser'           ,   /* 24 */
                        'seu'           ,   /* 25 */
                        'van'           ,   /* 26 */
                        'o'             ,   /* 27 */
                        'no'            ,   /* 28 */
                        "s'"            ,   /* 29 */
                        'seva'          ,   /* 30 */
                        'fou'           ,   /* 31 */
                        'entre'         ,   /* 32 */
                        'també'         ,   /* 33 */
                        'però'          ,   /* 34 */
                        'als'           ,   /* 35 */
                        'després'       ,   /* 36 */
                        'ha'            ,   /* 37 */
                        'aquest'        ,   /* 38 */
                        'fins'          ,   /* 39 */
                        'any'           ,   /* 40 */
                        'són'           ,   /* 41 */
                        'hi'            ,   /* 42 */
                        'pel'           ,   /* 43 */
                        'aquesta'       ,   /* 44 */
                        'durant'        ,   /* 45 */
                        'on'            ,   /* 46 */
                        'era'           ,   /* 47 */
                        'part'          ,   /* 48 */
                        'altres'        ,   /* 49 */
                        'anys'          ,   /* 50 */
                        'gran'          ,   /* 51 */
                        'ciutat'        ,   /* 52 */
                        'cap'           ,   /* 53 */
                        'des'           ,   /* 54 */
                        'seus'          ,   /* 55 */
                        'tot'           ,   /* 56 */
                        'estat'         ,   /* 57 */
                        'qual'          ,   /* 58 */
                        'segle'         ,   /* 59 */
                        'sobre'         ,   /* 60 */
                        'quan'          ,   /* 61 */
                        'guerra'        ,   /* 62 */
                        'ja'            ,   /* 63 */
                        'havia'         ,   /* 64 */
                        'molt'          ,   /* 65 */
                        'rei'           ,   /* 66 */
                        'dos'           ,   /* 67 */
                        'primer'        ,   /* 68 */
                        'nom'           ,   /* 69 */
                        'fer'           ,   /* 70 */
                        'se'            ,   /* 71 */
                        'així'          ,   /* 72 */
                        'li'            ,   /* 73 */
                        'sant'          ,   /* 74 */
                        'encara'        ,   /* 75 */
                        'pels'          ,   /* 76 */
                        'primera'       ,   /* 77 */
                        'seves'         ,   /* 78 */
                        'contra'        ,   /* 79 */
                        'té'            ,   /* 80 */
                        'partit'        ,   /* 81 */
                        'està'          ,   /* 82 */
                        'mateix'        ,   /* 83 */
                        'forma'         ,   /* 84 */
                        'pot'           ,   /* 85 */
                        'nord'          ,   /* 86 */
                        'tres'          ,   /* 87 */
                        'temps'         ,   /* 88 */
                        'fill'          ,   /* 89 */
                        'han'           ,   /* 90 */
                        'només'         ,   /* 91 */
                        'dues'          ,   /* 92 */
                        'si'            ,   /* 93 */
                        'sota'          ,   /* 94 */
                        'general'       ,   /* 95 */
                        'lloc'          ,   /* 96 */
                        'això'          ,   /* 97 */
                        'barcelona'     ,   /* 98 */
                        'alguns'        ,   /* 99 */
                        'govern'        ,   /* 100 */
                        'poder'         ,   /* 101 */
                        'uns'           ,   /* 102 */
                        'aquests'       ,   /* 103 */
                        'mort'          ,   /* 104 */
                        'nou'           ,   /* 105 */
                        'sud'           ,   /* 106 */
                        'tots'          ,   /* 107 */
                        'fet'           ,   /* 108 */
                        'sense'         ,   /* 109 */
                        'frança'        ,   /* 110 */
                        'grup'          ,   /* 111 */
                        'tant'          ,   /* 112 */
                        'terme'         ,   /* 113 */
                        'fa'            ,   /* 114 */
                        'tenir'         ,   /* 115 */
                        'segons'        ,   /* 116 */
                        'món'           ,   /* 117 */
                        'regne'         ,   /* 118 */
                        'exèrcit'       ,   /* 119 */
                        'segona'        ,   /* 120 */
                        'abans'         ,   /* 121 */
                        'mentre'        ,   /* 122 */
                        'quals'         ,   /* 123 */
                        'aquestes'      ,   /* 124 */
                        'família'       ,   /* 125 */
                        'catalunya'     ,   /* 126 */
                        'país'          ,   /* 127 */
                        'eren'          ,   /* 128 */
                        'poden'         ,   /* 129 */
                        'diferents'     ,   /* 130 */
                        'nova'          ,   /* 131 */
                        'molts'         ,   /* 132 */
                        'església'      ,   /* 133 */
                        'major'         ,   /* 134 */
                        'club'          ,   /* 135 */
                        'manera'        ,   /* 136 */
                        'estats'        ,   /* 137 */
                        'seua'          ,   /* 138 */
                        'diversos'      ,   /* 139 */
                        'grans'         ,   /* 140 */
                        'què'           ,   /* 141 */
                        'arribar'       ,   /* 142 */
                        'troba'         ,   /* 143 */
                        'població'      ,   /* 144 */
                        'sistema'       ,   /* 145 */
                        'poble'         ,   /* 146 */
                        'foren'         ,   /* 147 */
                        'època'         ,   /* 148 */
                        'haver'         ,   /* 149 */
                        'cada'          ,   /* 150 */
                        'eleccions'     ,   /* 151 */
                        'diverses'      ,   /* 152 */
                        'obra'          ,   /* 153 */
                        'partir'        ,   /* 154 */
                        'tipus'         ,   /* 155 */
                        'riu'           ,   /* 156 */
                        'vida'          ,   /* 157 */
                        'dia'           ,   /* 158 */
                        'quatre'        ,   /* 159 */
                        'poc'           ,   /* 160 */
                        'regió'         ,   /* 161 */
                        'exemple'       ,   /* 162 */
                        'batalla'       ,   /* 163 */
                        'altre'         ,   /* 164 */
                        'espanya'       ,   /* 165 */
                        'joan'          ,   /* 166 */
                        'actualment'    ,   /* 167 */
                        'tenen'         ,   /* 168 */
                        'dins'          ,   /* 169 */
                        'llavors'       ,   /* 170 */
                        'centre'        ,   /* 171 */
                        'algunes'       ,   /* 172 */
                        'important'     ,   /* 173 */
                        'altra'         ,   /* 174 */
                        'terra'         ,   /* 175 */
                        'antic'         ,   /* 176 */
                        'tenia'         ,   /* 177 */
                        'zona'          ,   /* 178 */
                        'obres'         ,   /* 179 */
                        'estava'        ,   /* 180 */
                        'pare'          ,   /* 181 */
                        'qui'           ,   /* 182 */
                        'ara'           ,   /* 183 */
                        'havien'        ,   /* 184 */
                        'començar'      ,   /* 185 */
                        'història'      ,   /* 186 */
                        'morir'         ,   /* 187 */
                        'nacional'      ,   /* 188 */
                        'final'         ,   /* 189 */
                        'música'        ,   /* 190 */
                        'majoria'       ,   /* 191 */
                        'europa'        ,   /* 192 */
                        'posteriorment' ,   /* 193 */
                        'alemanya'      ,   /* 194 */
                        'principal'     ,   /* 195 */
                        'finalment'     ,   /* 196 */
                        'passar'        ,   /* 197 */
                        'punt'          ,   /* 198 */
                        'territori'     ,   /* 199 */
                        'illa' );           /* 200 */
?>