<?php
/* Dutch - 200 - https://en.wiktionary.org/wiki/Wiktionary:Frequency_lists/Dutch_wordlist */
$aWords['nl'] = array ( 'nederlands',   /* 00 */
                        'ik'        ,   /* 01 */
                        'je'        ,   /* 02 */
                        'het'       ,   /* 03 */
                        'de'        ,   /* 04 */
                        'dat'       ,   /* 05 */
                        'is'        ,   /* 06 */
                        'een'       ,   /* 07 */
                        'niet'      ,   /* 08 */
                        'en'        ,   /* 09 */
                        'wat'       ,   /* 10 */
                        'van'       ,   /* 11 */
                        'we'        ,   /* 12 */
                        'in'        ,   /* 13 */
                        'ze'        ,   /* 14 */
                        'hij'       ,   /* 15 */
                        'op'        ,   /* 16 */
                        'te'        ,   /* 17 */
                        'zijn'      ,   /* 18 */
                        'er'        ,   /* 19 */
                        'maar'      ,   /* 20 */
                        'die'       ,   /* 21 */
                        'heb'       ,   /* 22 */
                        'me'        ,   /* 23 */
                        'met'       ,   /* 24 */
                        'voor'      ,   /* 25 */
                        'als'       ,   /* 26 */
                        'ben'       ,   /* 27 */
                        'was'       ,   /* 28 */
                        'dit'       ,   /* 29 */
                        'mijn'      ,   /* 30 */
                        'om'        ,   /* 31 */
                        'aan'       ,   /* 32 */
                        'jij'       ,   /* 33 */
                        'naar'      ,   /* 34 */
                        'dan'       ,   /* 35 */
                        'hier'      ,   /* 36 */
                        'weet'      ,   /* 37 */
                        'kan'       ,   /* 38 */
                        'geen'      ,   /* 39 */
                        'nog'       ,   /* 40 */
                        'moet'      ,   /* 41 */
                        'wil'       ,   /* 42 */
                        'wel'       ,   /* 43 */
                        'ja'        ,   /* 44 */
                        'zo'        ,   /* 45 */
                        'heeft'     ,   /* 46 */
                        'hebben'    ,   /* 47 */
                        'hem'       ,   /* 48 */
                        'goed'      ,   /* 49 */
                        'nee'       ,   /* 50 */
                        'waar'      ,   /* 51 */
                        'nu'        ,   /* 52 */
                        'hoe'       ,   /* 53 */
                        'ga'        ,   /* 54 */
                        'haar'      ,   /* 55 */
                        'uit'       ,   /* 56 */
                        'doen'      ,   /* 57 */
                        'ook'       ,   /* 58 */
                        'over'      ,   /* 59 */
                        'bent'      ,   /* 60 */
                        'mij'       ,   /* 61 */
                        'gaan'      ,   /* 62 */
                        'of'        ,   /* 63 */
                        'kom'       ,   /* 64 */
                        'zou'       ,   /* 65 */
                        'al'        ,   /* 66 */
                        'bij'       ,   /* 67 */
                        'daar'      ,   /* 68 */
                        'ons'       ,   /* 69 */
                        'jullie'    ,   /* 70 */
                        'hebt'      ,   /* 71 */
                        'gaat'      ,   /* 72 */
                        'iets'      ,   /* 73 */
                        'zal'       ,   /* 74 */
                        'meer'      ,   /* 75 */
                        'waarom'    ,   /* 76 */
                        'had'       ,   /* 77 */
                        'deze'      ,   /* 78 */
                        'laat'      ,   /* 79 */
                        'moeten'    ,   /* 80 */
                        'jou'       ,   /* 81 */
                        'doe'       ,   /* 82 */
                        'wie'       ,   /* 83 */
                        'kunnen'    ,   /* 84 */
                        'alles'     ,   /* 85 */
                        'denk'      ,   /* 86 */
                        'door'      ,   /* 87 */
                        'echt'      ,   /* 88 */
                        'alleen'    ,   /* 89 */
                        'eens'      ,   /* 90 */
                        'dus'       ,   /* 91 */
                        'weg'       ,   /* 92 */
                        'oké'       ,   /* 93 */
                        'zien'      ,   /* 94 */
                        'toch'      ,   /* 95 */
                        'man'       ,   /* 96 */
                        'nooit'     ,   /* 97 */
                        'terug'     ,   /* 98 */
                        'laten'     ,   /* 99 */
                        'nou'       ,   /* 100 */
                        'mee'       ,   /* 101 */
                        'misschien' ,   /* 102 */
                        'even'      ,   /* 103 */
                        'iemand'    ,   /* 104 */
                        'komt'      ,   /* 105 */
                        'niets'     ,   /* 106 */
                        'zei'       ,   /* 107 */
                        'hou'       ,   /* 108 */
                        'komen'     ,   /* 109 */
                        'mensen'    ,   /* 110 */
                        'onze'      ,   /* 111 */
                        'nodig'     ,   /* 112 */
                        'tot'       ,   /* 113 */
                        'worden'    ,   /* 114 */
                        'veel'      ,   /* 115 */
                        'weten'     ,   /* 116 */
                        'leven'     ,   /* 117 */
                        'wij'       ,   /* 118 */
                        'weer'      ,   /* 119 */
                        'gewoon'    ,   /* 120 */
                        'kijk'      ,   /* 121 */
                        'zeggen'    ,   /* 122 */
                        'tijd'      ,   /* 123 */
                        'zeg'       ,   /* 124 */
                        'twee'      ,   /* 125 */
                        'toen'      ,   /* 126 */
                        'tegen'     ,   /* 127 */
                        'zit'       ,   /* 128 */
                        'net'       ,   /* 129 */
                        'dood'      ,   /* 130 */
                        'uw'        ,   /* 131 */
                        'wordt'     ,   /* 132 */
                        'maken'     ,   /* 133 */
                        'mag'       ,   /* 134 */
                        'één'       ,   /* 135 */
                        'omdat'     ,   /* 136 */
                        'gedaan'    ,   /* 137 */
                        'heel'      ,   /* 138 */
                        'af'        ,   /* 139 */
                        'altijd'    ,   /* 140 */
                        'jouw'      ,   /* 141 */
                        'zeker'     ,   /* 142 */
                        'geef'      ,   /* 143 */
                        'zie'       ,   /* 144 */
                        'wacht'     ,   /* 145 */
                        'allemaal'  ,   /* 146 */
                        'jaar'      ,   /* 147 */
                        'doet'      ,   /* 148 */
                        'dag'       ,   /* 149 */
                        'zij'       ,   /* 150 */
                        'hun'       ,   /* 151 */
                        'huis'      ,   /* 152 */
                        'vader'     ,   /* 153 */
                        'dank'      ,   /* 154 */
                        'dacht'     ,   /* 155 */
                        'kunt'      ,   /* 156 */
                        'zoals'     ,   /* 157 */
                        'vrouw'     ,   /* 158 */
                        'keer'      ,   /* 159 */
                        'anders'    ,   /* 160 */
                        'andere'    ,   /* 161 */
                        'willen'    ,   /* 162 */
                        'erg'       ,   /* 163 */
                        'spijt'     ,   /* 164 */
                        'bedankt'   ,   /* 165 */
                        'niemand'   ,   /* 166 */
                        'wilt'      ,   /* 167 */
                        'geld'      ,   /* 168 */
                        'zitten'    ,   /* 169 */
                        'niks'      ,   /* 170 */
                        'iedereen'  ,   /* 171 */
                        'hé'        ,   /* 172 */
                        'binnen'    ,   /* 173 */
                        'staat'     ,   /* 174 */
                        'wilde'     ,   /* 175 */
                        'zich'      ,   /* 176 */
                        'beter'     ,   /* 177 */
                        'werk'      ,   /* 178 */
                        'praten'    ,   /* 179 */
                        'god'       ,   /* 180 */
                        'gezien'    ,   /* 181 */
                        'zullen'    ,   /* 182 */
                        'waren'     ,   /* 183 */
                        'maak'      ,   /* 184 */
                        'neem'      ,   /* 185 */
                        'vinden'    ,   /* 186 */
                        'vind'      ,   /* 187 */
                        'moeder'    ,   /* 188 */
                        'kon'       ,   /* 189 */
                        'oh'        ,   /* 190 */
                        'uur'       ,   /* 191 */
                        'klaar'     ,   /* 192 */
                        'genoeg'    ,   /* 193 */
                        'helpen'    ,   /* 194 */
                        'hele'      ,   /* 195 */
                        'drie'      ,   /* 196 */
                        'vast'      ,   /* 197 */
                        'na'        ,   /* 198 */
                        'hallo'     ,   /* 199 */
                        'leuk' );       /* 200 */
?>