<?php
/* English - 200 - https://en.m.wikipedia.org/wiki/Most_common_words_in_English */
$aWords['en'] = array ( 'english'   ,   /* 00 */
                        'the'       ,   /* 01 */
                        'be'        ,   /* 02 */
                        'to'        ,   /* 03 */
                        'of'        ,   /* 04 */
                        'and'       ,   /* 05 */
                        'a'         ,   /* 06 */
                        'in'        ,   /* 07 */
                        'that'      ,   /* 08 */
                        'have'      ,   /* 09 */
                        'I'         ,   /* 10 */
                        'it'        ,   /* 11 */
                        'for'       ,   /* 12 */
                        'not'       ,   /* 13 */
                        'on'        ,   /* 14 */
                        'with'      ,   /* 15 */
                        'he'        ,   /* 16 */
                        'as'        ,   /* 17 */
                        'you'       ,   /* 18 */
                        'do'        ,   /* 19 */
                        'at'        ,   /* 20 */
                        'this'      ,   /* 21 */
                        'but'       ,   /* 22 */
                        'his'       ,   /* 23 */
                        'by'        ,   /* 24 */
                        'from'      ,   /* 25 */
                        'they'      ,   /* 26 */
                        'we'        ,   /* 27 */
                        'say'       ,   /* 28 */
                        'her'       ,   /* 29 */
                        'she'       ,   /* 30 */
                        'or'        ,   /* 31 */
                        'wand'      ,   /* 32 */
                        'will'      ,   /* 33 */
                        'my'        ,   /* 34 */
                        'one'       ,   /* 35 */
                        'all'       ,   /* 36 */
                        'would'     ,   /* 37 */
                        'there'     ,   /* 38 */
                        'their'     ,   /* 39 */
                        'what'      ,   /* 40 */
                        'so'        ,   /* 41 */
                        'up'        ,   /* 42 */
                        'out'       ,   /* 43 */
                        'if'        ,   /* 44 */
                        'about'     ,   /* 45 */
                        'who'       ,   /* 46 */
                        'get'       ,   /* 47 */
                        'which'     ,   /* 48 */
                        'go'        ,   /* 49 */
                        'me'        ,   /* 50 */
                        'when'      ,   /* 51 */
                        'make'      ,   /* 52 */
                        'can'       ,   /* 53 */
                        'like'      ,   /* 54 */
                        'time'      ,   /* 55 */
                        'no'        ,   /* 56 */
                        'just'      ,   /* 57 */
                        'him'       ,   /* 58 */
                        'know'      ,   /* 59 */
                        'take'      ,   /* 60 */
                        'people'    ,   /* 61 */
                        'into'      ,   /* 62 */
                        'year'      ,   /* 63 */
                        'your'      ,   /* 64 */
                        'good'      ,   /* 65 */
                        'some'      ,   /* 66 */
                        'could'     ,   /* 67 */
                        'them'      ,   /* 68 */
                        'see'       ,   /* 69 */
                        'other'     ,   /* 70 */
                        'than'      ,   /* 71 */
                        'then'      ,   /* 72 */
                        'now'       ,   /* 73 */
                        'look'      ,   /* 74 */
                        'only'      ,   /* 75 */
                        'come'      ,   /* 76 */
                        'its'       ,   /* 77 */
                        'over'      ,   /* 78 */
                        'think'     ,   /* 79 */
                        'also'      ,   /* 80 */
                        'back'      ,   /* 81 */
                        'after'     ,   /* 82 */
                        'use'       ,   /* 83 */
                        'two'       ,   /* 84 */
                        'how'       ,   /* 85 */
                        'our'       ,   /* 86 */
                        'work'      ,   /* 87 */
                        'first'     ,   /* 88 */
                        'well'      ,   /* 89 */
                        'way'       ,   /* 90 */
                        'even'      ,   /* 91 */
                        'new'       ,   /* 92 */
                        'want'      ,   /* 93 */
                        'because'   ,   /* 94 */
                        'any'       ,   /* 95 */
                        'these'     ,   /* 96 */
                        'give'      ,   /* 97 */
                        'day'       ,   /* 98 */
                        'most'      ,   /* 99 */
                        'us'        ,   /* 100 */
                        'those'     ,   /* 101 */
                        'tell'      ,   /* 102 */
                        'one'       ,   /* 103 */
                        'very'      ,   /* 104 */
                        'her'       ,   /* 105 */
                        'even'      ,   /* 106 */
                        'back'      ,   /* 107 */
                        'any'       ,   /* 108 */
                        'good'      ,   /* 109 */
                        'woman'     ,   /* 110 */
                        'through'   ,   /* 111 */
                        'us'        ,   /* 112 */
                        'life'      ,   /* 113 */
                        'child'     ,   /* 114 */
                        'there'     ,   /* 115 */
                        'work'      ,   /* 116 */
                        'down'      ,   /* 117 */
                        'may'       ,   /* 118 */
                        'after'     ,   /* 119 */
                        'should'    ,   /* 120 */
                        'call'      ,   /* 121 */
                        'world'     ,   /* 122 */
                        'over'      ,   /* 123 */
                        'school'    ,   /* 124 */
                        'still'     ,   /* 125 */
                        'try'       ,   /* 126 */
                        'in'        ,   /* 127 */
                        'as'        ,   /* 128 */
                        'last'      ,   /* 129 */
                        'ask'       ,   /* 130 */
                        'need'      ,   /* 131 */
                        'too'       ,   /* 132 */
                        'feel'      ,   /* 133 */
                        'three'     ,   /* 134 */
                        'when'      ,   /* 135 */
                        'state'     ,   /* 136 */
                        'never'     ,   /* 137 */
                        'become'    ,   /* 138 */
                        'between'   ,   /* 139 */
                        'high'      ,   /* 140 */
                        'really'    ,   /* 141 */
                        'something' ,   /* 142 */
                        'most'      ,   /* 143 */
                        'another'   ,   /* 144 */
                        'much'      ,   /* 145 */
                        'family'    ,   /* 146 */
                        'own'       ,   /* 147 */
                        'out'       ,   /* 148 */
                        'leave'     ,   /* 149 */
                        'put'       ,   /* 150 */
                        'old'       ,   /* 151 */
                        'while'     ,   /* 152 */
                        'mean'      ,   /* 153 */
                        'on'        ,   /* 154 */
                        'keep'      ,   /* 155 */
                        'student'   ,   /* 156 */
                        'why'       ,   /* 157 */
                        'let'       ,   /* 158 */
                        'great'     ,   /* 159 */
                        'same'      ,   /* 160 */
                        'big'       ,   /* 161 */
                        'group'     ,   /* 162 */
                        'begin'     ,   /* 163 */
                        'seem'      ,   /* 164 */
                        'country'   ,   /* 165 */
                        'help'      ,   /* 166 */
                        'talk'      ,   /* 167 */
                        'where'     ,   /* 168 */
                        'turn'      ,   /* 169 */
                        'problem'   ,   /* 170 */
                        'every'     ,   /* 171 */
                        'start'     ,   /* 172 */
                        'hand'      ,   /* 173 */
                        'might'     ,   /* 174 */
                        'american'  ,   /* 175 */
                        'show'      ,   /* 176 */
                        'part'      ,   /* 177 */
                        'about'     ,   /* 178 */
                        'against'   ,   /* 179 */
                        'place'     ,   /* 180 */
                        'over'      ,   /* 181 */
                        'such'      ,   /* 182 */
                        'again'     ,   /* 183 */
                        'few'       ,   /* 184 */
                        'case'      ,   /* 185 */
                        'most'      ,   /* 186 */
                        'week'      ,   /* 187 */
                        'company'   ,   /* 188 */
                        'where'     ,   /* 189 */
                        'system'    ,   /* 190 */
                        'each'      ,   /* 191 */
                        'right'     ,   /* 192 */
                        'program'   ,   /* 193 */
                        'hear'      ,   /* 194 */
                        'so'        ,   /* 195 */
                        'question'  ,   /* 196 */
                        'during'    ,   /* 197 */
                        'work'      ,   /* 198 */
                        'play'      ,   /* 199 */
                        'government' ); /* 200 */
?>