<?php
/* French - 200 - https://fr.wiktionary.org/wiki/Wiktionnaire:Listes_de_fr%C3%A9quence/wortschatz-fr-1-2000 */
$aWords['fr'] = array ( 'français'  ,   /* 00 */
                        'française' ,   /* 00bis */
                        'de'        ,   /* 01 */
                        'la'        ,   /* 02 */
                        'le'        ,   /* 03 */
                        'être'      ,   /* 04 */
                        'et'        ,   /* 05 */
                        'les'       ,   /* 06 */
                        'des'       ,   /* 07 */
                        'en'        ,   /* 08 */
                        'un'        ,   /* 09 */
                        'du'        ,   /* 10 */
                        'une'       ,   /* 11 */
                        'que'       ,   /* 12 */
                        'est'       ,   /* 13 */
                        'pour'      ,   /* 14 */
                        'qui'       ,   /* 15 */
                        'dans'      ,   /* 16 */
                        'a'         ,   /* 17 */
                        'par'       ,   /* 18 */
                        'plus'      ,   /* 19 */
                        'pas'       ,   /* 20 */
                        'au'        ,   /* 21 */
                        'sur'       ,   /* 22 */
                        'ne'        ,   /* 23 */
                        'se'        ,   /* 24 */
                        'ce'        ,   /* 25 */
                        'ils'       ,   /* 26 */
                        'sont'      ,   /* 27 */
                        'ou'        ,   /* 28 */
                        'avec'      ,   /* 29 */
                        'son'       ,   /* 30 */
                        'il'        ,   /* 31 */
                        'aux'       ,   /* 32 */
                        'd\'un'     ,   /* 33 */
                        'ont'       ,   /* 34 */
                        'ses'       ,   /* 35 */
                        'mais'      ,   /* 36 */
                        'comme'     ,   /* 37 */
                        'on'        ,   /* 38 */
                        'tout'      ,   /* 39 */
                        'nous'      ,   /* 40 */
                        'sa'        ,   /* 41 */
                        'mais'      ,   /* 42 */
                        'fait'      ,   /* 43 */
                        'été'       ,   /* 44 */
                        'aussi'     ,   /* 45 */
                        'leur'      ,   /* 46 */
                        'bien'      ,   /* 47 */
                        'peut'      ,   /* 48 */
                        'ces'       ,   /* 49 */
                        'y'         ,   /* 50 */
                        'deux'      ,   /* 51 */
                        'ans'       ,   /* 52 */
                        'encore'    ,   /* 53 */
                        'n\'est'    ,   /* 54 */
                        'marché'    ,   /* 55 */
                        'donc'      ,   /* 56 */
                        'cours'     ,   /* 57 */
                        'qu\'il'    ,   /* 58 */
                        'moins'     ,   /* 59 */
                        'sans'      ,   /* 60 */
                        'c\'est'    ,   /* 61 */
                        'et'        ,   /* 62 */
                        'si'        ,   /* 63 */
                        'entre'     ,   /* 64 */
                        'un'        ,   /* 65 */
                        'ce'        ,   /* 66 */
                        'faire'     ,   /* 67 */
                        'elle'      ,   /* 68 */
                        'peu'       ,   /* 69 */
                        'vous'      ,   /* 70 */
                        'une'       ,   /* 71 */
                        'prix'      ,   /* 72 */
                        'on'        ,   /* 73 */
                        'dont'      ,   /* 74 */
                        'lui'       ,   /* 75 */
                        'également' ,   /* 76 */
                        'dans'      ,   /* 77 */
                        'effet'     ,   /* 78 */
                        'pays'      ,   /* 79 */
                        'cas'       ,   /* 80 */
                        'mois'      ,   /* 81  */
                        'leurs'     ,   /* 82  */
                        'taux'      ,   /* 83  */
                        'années'    ,   /* 84  */
                        'temps'     ,   /* 85  */
                        'groupe'    ,   /* 86  */
                        'ainsi'     ,   /* 87  */
                        'toujours'  ,   /* 88  */
                        'société'   ,   /* 89  */
                        'depuis'    ,   /* 90  */
                        'tous'      ,   /* 91  */
                        'soit'      ,   /* 92  */
                        'faut'      ,   /* 93  */
                        'fois'      ,   /* 94  */
                        'quelques'  ,   /* 95  */
                        'sera'      ,   /* 96  */
                        'entreprise',   /* 97  */
                        'contre'    ,   /* 98  */
                        'francs'    ,   /* 99  */
                        'je'        ,   /* 100 */
                        'actions'   ,   /* 101 */
                        'affaires'  ,   /* 102 */
                        'agit'      ,   /* 103 */
                        'alors'     ,   /* 104 */
                        'an'        ,   /* 105 */
                        'année'     ,   /* 106 */
                        'au'        ,   /* 107 */
                        'aujourd'   ,   /* 108 */
                        'autre'     ,   /* 109 */
                        'autres'    ,   /* 110 */
                        'avait'     ,   /* 111 */
                        'avant'     ,   /* 112 */
                        'avec'      ,   /* 113 */
                        'avoir'     ,   /* 114 */
                        'avons'     ,   /* 115 */
                        'baisse'    ,   /* 116 */
                        'banque'    ,   /* 117 */
                        'base'      ,   /* 118 */
                        'beaucoup'  ,   /* 119 */
                        'belge'     ,   /* 120 */
                        'bon'       ,   /* 121 */
                        'bourse'    ,   /* 122 */
                        'bénéfice'  ,   /* 123 */
                        'cela'      ,   /* 124 */
                        'celui'     ,   /* 125 */
                        'certains'  ,   /* 126 */
                        'ces'       ,   /* 127 */
                        'cet'       ,   /* 128 */
                        'cette'     ,   /* 129 */
                        'chaque'    ,   /* 130 */
                        'chez'      ,   /* 131 */
                        'chiffre'   ,   /* 132 */
                        'compte'    ,   /* 133 */
                        'croissance',   /* 134 */
                        'dernier'   ,   /* 135 */
                        'des'       ,   /* 136 */
                        'devrait'   ,   /* 137 */
                        'doit'      ,   /* 138 */
                        'début'     ,   /* 139 */
                        'elle'      ,   /* 140 */
                        'entreprise',   /* 141 */
                        'exemple'   ,   /* 142 */
                        'fin'       ,   /* 143 */
                        'fonds'     ,   /* 144 */
                        'france'    ,   /* 145 */
                        'grand'     ,   /* 146 */
                        'grande'    ,   /* 147 */
                        'hausse'    ,   /* 148 */
                        'ils'       ,   /* 149 */
                        'jamais'    ,   /* 150 */
                        'jour'      ,   /* 151 */
                        'lors'      ,   /* 152 */
                        'mieux'     ,   /* 153 */
                        'milliards' ,   /* 154 */
                        'monde'     ,   /* 155 */
                        'niveau'    ,   /* 156 */
                        'nombre'    ,   /* 157 */
                        'non'       ,   /* 158 */
                        'nos'       ,   /* 159 */
                        'notre'     ,   /* 160 */
                        'nous'      ,   /* 161 */
                        'nouveau'   ,   /* 162 */
                        'nouvelle'  ,   /* 163 */
                        'par'       ,   /* 164 */
                        'part'      ,   /* 165 */
                        'partie'    ,   /* 166 */
                        'permet'    ,   /* 167 */
                        'personnes' ,   /* 168 */
                        'peuvent'   ,   /* 169 */
                        'place'     ,   /* 170 */
                        'plusieurs' ,   /* 171 */
                        'point'     ,   /* 172 */
                        'politique' ,   /* 173 */
                        'pourrait'  ,   /* 174 */
                        'premier'   ,   /* 175 */
                        'production',   /* 176 */
                        'produit'   ,   /* 177 */
                        'produits'  ,   /* 178 */
                        'qualité'   ,   /* 179 */
                        'quelque'   ,   /* 180 */
                        'rapport'   ,   /* 181 */
                        'reste'     ,   /* 182 */
                        'rien'      ,   /* 183 */
                        'risque'    ,   /* 184 */
                        'résultats' ,   /* 185 */
                        'secteur'   ,   /* 186 */
                        'si'        ,   /* 187 */
                        'sous'      ,   /* 188 */
                        'souvent'   ,   /* 189 */
                        'surtout'   ,   /* 190 */
                        'terme'     ,   /* 191 */
                        'toute'     ,   /* 192 */
                        'toutes'    ,   /* 193 */
                        'travail'   ,   /* 194 */
                        'trois'     ,   /* 195 */
                        'trop'      ,   /* 196 */
                        'va'        ,   /* 197 */
                        'valeur'    ,   /* 198 */
                        'vente'     ,   /* 199 */
                        'vers' );       /* 200 */
?>