<?php
/* German - 100 - https://fr.wiktionary.org/wiki/Wiktionnaire:Listes_de_fr%C3%A9quence/wortschatz-de-1-2000 */
$aWords['de'] = array ( 'der'           ,   /* 01 */
                        'und'           ,   /* 02 */
                        'die'           ,   /* 03 */
                        'in'            ,   /* 04 */
                        'ist'           ,   /* 05 */
                        'von'           ,   /* 06 */
                        'den'           ,   /* 07 */
                        'des'           ,   /* 08 */
                        'eine'          ,   /* 09 */
                        'im'            ,   /* 10 */
                        'ein'           ,   /* 11 */
                        'mit'           ,   /* 12 */
                        'das'           ,   /* 13 */
                        'zu'            ,   /* 14 */
                        'für'           ,   /* 15 */
                        'dem'           ,   /* 16 */
                        'sich'          ,   /* 17 */
                        'auf'           ,   /* 18 */
                        'als'           ,   /* 19 */
                        'auch'          ,   /* 20 */
                        'wird'          ,   /* 21 */
                        'oder'          ,   /* 22 */
                        'aus'           ,   /* 23 */
                        'wurde'         ,   /* 24 */
                        'werden'        ,   /* 25 */
                        'sind'          ,   /* 26 */
                        'an'            ,   /* 27 */
                        'einer'         ,   /* 28 */
                        'nicht'         ,   /* 29 */
                        'durch'         ,   /* 30 */
                        'nach'          ,   /* 31 */
                        'bei'           ,   /* 32 */
                        'es'            ,   /* 33 */
                        'war'           ,   /* 34 */
                        'zum'           ,   /* 35 */
                        'er'            ,   /* 36 */
                        'zur'           ,   /* 37 */
                        'am'            ,   /* 38 */
                        'einem'         ,   /* 39 */
                        'einen'         ,   /* 40 */
                        'sie'           ,   /* 41 */
                        'bis'           ,   /* 42 */
                        'man'           ,   /* 43 */
                        'über'          ,   /* 44 */
                        'um'            ,   /* 45 */
                        'dass'          ,   /* 46 */
                        'wie'           ,   /* 47 */
                        'hat'           ,   /* 48 */
                        'eines'         ,   /* 49 */
                        'nur'           ,   /* 50 */
                        'oder'          ,   /* 51 */
                        'aber'          ,   /* 52 */
                        'vor'           ,   /* 53 */
                        'zur'           ,   /* 54 */
                        'bis'           ,   /* 55 */
                        'mehr'          ,   /* 56 */
                        'durch'         ,   /* 57 */
                        'man'           ,   /* 58 */
                        'sein'          ,   /* 59 */
                        'wurde'         ,   /* 60 */
                        'sei'           ,   /* 61 */
                        'in'            ,   /* 62 */
                        'prozent'       ,   /* 63 */
                        'hatte'         ,   /* 64 */
                        'kann'          ,   /* 65 */
                        'gegen'         ,   /* 66 */
                        'vom'           ,   /* 67 */
                        'können'        ,   /* 68 */
                        'schon'         ,   /* 69 */
                        'wenn'          ,   /* 70 */
                        'habe'          ,   /* 71 */
                        'seine'         ,   /* 72 */
                        'mark'          ,   /* 73 */
                        'ihre'          ,   /* 74 */
                        'dann'          ,   /* 75 */
                        'unter'         ,   /* 76 */
                        'wir'           ,   /* 77 */
                        'soll'          ,   /* 78 */
                        'ich'           ,   /* 79 */
                        'eines'         ,   /* 80 */
                        'es'            ,   /* 81 */
                        'jahr'          ,   /* 82 */
                        'zwei'          ,   /* 83 */
                        'jahren'        ,   /* 84 */
                        'diese'         ,   /* 85 */
                        'dieser'        ,   /* 86 */
                        'wieder'        ,   /* 87 */
                        'keine'         ,   /* 88 */
                        'uhr'           ,   /* 89 */
                        'seiner'        ,   /* 90 */
                        'worden'        ,   /* 91 */
                        'und'           ,   /* 92 */
                        'will'          ,   /* 93 */
                        'zwischen'      ,   /* 94 */
                        'im'            ,   /* 95 */
                        'immer'         ,   /* 96 */
                        'millionen'     ,   /* 97 */
                        'ein'           ,   /* 98 */
                        'was'           ,   /* 99 */
                        'sagte'         ,   /* 100 */
                        'er'            ,   /* 101 */
                        'gibt'          ,   /* 102 */
                        'alle'          ,   /* 103 */
                        'dm'            ,   /* 104 */
                        'diesem'        ,   /* 105 */
                        'seit'          ,   /* 106 */
                        'muß'           ,   /* 107 */
                        'wurden'        ,   /* 108 */
                        'beim'          ,   /* 109 */
                        'doch'          ,   /* 110 */
                        'jetzt'         ,   /* 111 */
                        'waren'         ,   /* 112 */
                        'drei'          ,   /* 113 */
                        'jahre'         ,   /* 114 */
                        'mit'           ,   /* 115 */
                        'neue'          ,   /* 116 */
                        'neuen'         ,   /* 117 */
                        'damit'         ,   /* 118 */
                        'bereits'       ,   /* 119 */
                        'da'            ,   /* 120 */
                        'auch'          ,   /* 121 */
                        'ihr'           ,   /* 122 */
                        'seinen'        ,   /* 123 */
                        'müssen'        ,   /* 124 */
                        'ab'            ,   /* 125 */
                        'ihrer'         ,   /* 126 */
                        'nach'          ,   /* 127 */
                        'ohne'          ,   /* 128 */
                        'sondern'       ,   /* 129 */
                        'selbst'        ,   /* 130 */
                        'ersten'        ,   /* 131 */
                        'nun'           ,   /* 132 */
                        'etwa'          ,   /* 133 */
                        'bei'           ,   /* 134 */
                        'heute'         ,   /* 135 */
                        'ihren'         ,   /* 136 */
                        'weil'          ,   /* 137 */
                        'ihm'           ,   /* 138 */
                        'seien'         ,   /* 139 */
                        'menschen'      ,   /* 140 */
                        'deutschland'   ,   /* 141 */
                        'anderen'       ,   /* 142 */
                        'werde'         ,   /* 143 */
                        'ich'           ,   /* 144 */
                        'sagt'          ,   /* 145 */
                        'wir'           ,   /* 146 */
                        'eine'          ,   /* 147 */
                        'rund'          ,   /* 148 */
                        'für'           ,   /* 149 */
                        'aber'          ,   /* 150 */
                        'ihn'           ,   /* 151 */
                        'ende'          ,   /* 152 */
                        'jedoch'        ,   /* 153 */
                        'zeit'          ,   /* 154 */
                        'sollen'        ,   /* 155 */
                        'ins'           ,   /* 156 */
                        'wenn'          ,   /* 157 */
                        'so'            ,   /* 158 */
                        'seinem'        ,   /* 159 */
                        'uns'           ,   /* 160 */
                        'stadt'         ,   /* 161 */
                        'geht'          ,   /* 162 */
                        'doch'          ,   /* 163 */
                        'sehr'          ,   /* 164 */
                        'hier'          ,   /* 165 */
                        'ganz'          ,   /* 166 */
                        'erst'          ,   /* 167 */
                        'wollen'        ,   /* 168 */
                        'berlin'        ,   /* 169 */
                        'vorallem'      ,   /* 170 */
                        'sowie'         ,   /* 171 */
                        'hatten'        ,   /* 172 */
                        'kein'          ,   /* 173 */
                        'deutschen'     ,   /* 174 */
                        'machen'        ,   /* 175 */
                        'lassen'        ,   /* 176 */
                        'als'           ,   /* 177 */
                        'unternehmen'   ,   /* 178 */
                        'andere'        ,   /* 179 */
                        'ob'            ,   /* 180 */
                        'dieses'        ,   /* 181 */
                        'steht'         ,   /* 182 */
                        'dabei'         ,   /* 183 */
                        'wegen'         ,   /* 184 */
                        'weiter'        ,   /* 185 */
                        'denn'          ,   /* 186 */
                        'beiden'        ,   /* 187 */
                        'einmal'        ,   /* 188 */
                        'etwas'         ,   /* 189 */
                        'wie'           ,   /* 190 */
                        'nichts'        ,   /* 191 */
                        'allerdings'    ,   /* 192 */
                        'vier'          ,   /* 193 */
                        'gut'           ,   /* 194 */
                        'viele'         ,   /* 195 */
                        'wo'            ,   /* 196 */
                        'viel'          ,   /* 197 */
                        'dort'          ,   /* 198 */
                        'alles'         ,   /* 199 */
                        'auf' );            /* 200 */
?>