<?php
/* Italian - 200 - https://en.wiktionary.org/wiki/Wiktionary:Frequency_lists/Italian1000 */
$aWords['it'] = array ( 'non'       ,   /* 001 */
                        'di'        ,   /* 002 */
                        'che'       ,   /* 003 */
                        'la'        ,   /* 004 */
                        'il'        ,   /* 005 */
                        'un'        ,   /* 006 */
                        'per'       ,   /* 007 */
                        'in'        ,   /* 008 */
                        'una'       ,   /* 009 */
                        'mi'        ,   /* 010 */
                        'sono'      ,   /* 011 */
                        'ho'        ,   /* 012 */
                        'ma'        ,   /* 013 */
                        'lo'        ,   /* 014 */
                        'ha'        ,   /* 015 */
                        'le'        ,   /* 016 */
                        'si'        ,   /* 017 */
                        'ti'        ,   /* 018 */
                        'con'       ,   /* 019 */
                        'cosa'      ,   /* 020 */
                        'se'        ,   /* 021 */
                        'io'        ,   /* 022 */
                        'come'      ,   /* 023 */
                        'da'        ,   /* 024 */
                        'ci'        ,   /* 025 */
                        'no'        ,   /* 026 */
                        'questo'    ,   /* 027 */
                        'qui'       ,   /* 028 */
                        'hai'       ,   /* 029 */
                        'sei'       ,   /* 030 */
                        'del'       ,   /* 031 */
                        'bene'      ,   /* 032 */
                        'tu'        ,   /* 033 */
                        'sì'        ,   /* 034 */
                        'me'        ,   /* 035 */
                        'più'       ,   /* 036 */
                        'al'        ,   /* 037 */
                        'mio'       ,   /* 038 */
                        'perché'    ,   /* 039 */
                        'lei'       ,   /* 040 */
                        'solo'      ,   /* 041 */
                        'te'        ,   /* 042 */
                        'era'       ,   /* 043 */
                        'gli'       ,   /* 044 */
                        'tutto'     ,   /* 045 */
                        'della'     ,   /* 046 */
                        'così'      ,   /* 047 */
                        'mia'       ,   /* 048 */
                        'ne'        ,   /* 049 */
                        'questa'    ,   /* 050 */
                        'fare'      ,   /* 051 */
                        'quando'    ,   /* 052 */
                        'ora'       ,   /* 053 */
                        'fatto'     ,   /* 054 */
                        'essere'    ,   /* 055 */
                        'so'        ,   /* 056 */
                        'mai'       ,   /* 057 */
                        'chi'       ,   /* 058 */
                        'alla'      ,   /* 059 */
                        'tutti'     ,   /* 060 */
                        'molto'     ,   /* 061 */
                        'dei'       ,   /* 062 */
                        'anche'     ,   /* 063 */
                        'detto'     ,   /* 064 */
                        'quello'    ,   /* 065 */
                        'va'        ,   /* 066 */
                        'niente'    ,   /* 067 */
                        'grazie'    ,   /* 068 */
                        'lui'       ,   /* 069 */
                        'voglio'    ,   /* 070 */
                        'abbiamo'   ,   /* 071 */
                        'stato'     ,   /* 072 */
                        'nel'       ,   /* 073 */
                        'suo'       ,   /* 074 */
                        'dove'      ,   /* 075 */
                        'posso'     ,   /* 076 */
                        'oh'        ,   /* 077 */
                        'prima'     ,   /* 078 */
                        'allora'    ,   /* 079 */
                        'siamo'     ,   /* 080 */
                        'uno'       ,   /* 081 */
                        'sua'       ,   /* 082 */
                        'tuo'       ,   /* 083 */
                        'hanno'     ,   /* 084 */
                        'noi'       ,   /* 085 */
                        'sta'       ,   /* 086 */
                        'fa'        ,   /* 087 */
                        'due'       ,   /* 088 */
                        'vuoi'      ,   /* 089 */
                        'ancora'    ,   /* 090 */
                        'qualcosa'  ,   /* 091 */
                        'vero'      ,   /* 092 */
                        'casa'      ,   /* 093 */
                        'sia'       ,   /* 094 */
                        'su'        ,   /* 095 */
                        'tua'       ,   /* 096 */
                        'sempre'    ,   /* 097 */
                        'forse'     ,   /* 098 */
                        'dire'      ,   /* 099 */
                        'vi'        ,   /* 100 */
                        'loro'      ,   /* 101 */
                        'altro'     ,   /* 102 */
                        'sai'       ,   /* 103 */
                        'stai'      ,   /* 104 */
                        'devo'      ,   /* 105 */
                        'quella'    ,   /* 106 */
                        'vita'      ,   /* 107 */
                        'quel'      ,   /* 108 */
                        'delle'     ,   /* 109 */
                        'tempo'     ,   /* 110 */
                        'andare'    ,   /* 111 */
                        'certo'     ,   /* 112 */
                        'poi'       ,   /* 113 */
                        'nella'     ,   /* 114 */
                        'uomo'      ,   /* 115 */
                        'signore'   ,   /* 116 */
                        'ad'        ,   /* 117 */
                        'può'       ,   /* 118 */
                        'credo'     ,   /* 119 */
                        'voi'       ,   /* 120 */
                        'già'       ,   /* 121 */
                        'adesso'    ,   /* 122 */
                        'andiamo'   ,   /* 123 */
                        'anni'      ,   /* 124 */
                        'visto'     ,   /* 125 */
                        'fuori'     ,   /* 126 */
                        'proprio'   ,   /* 127 */
                        'parte'     ,   /* 128 */
                        'davvero'   ,   /* 129 */
                        'vuole'     ,   /* 130 */
                        'li'        ,   /* 131 */
                        'sto'       ,   /* 132 */
                        'quanto'    ,   /* 133 */
                        'volta'     ,   /* 134 */
                        'via'       ,   /* 135 */
                        'sul'       ,   /* 136 */
                        'dio'       ,   /* 137 */
                        'sarà'      ,   /* 138 */
                        'dopo'      ,   /* 139 */
                        'senza'     ,   /* 140 */
                        'cose'      ,   /* 141 */
                        'nessuno'   ,   /* 142 */
                        'fai'       ,   /* 143 */
                        'giorno'    ,   /* 144 */
                        'ed'        ,   /* 145 */
                        'meglio'    ,   /* 146 */
                        'padre'     ,   /* 147 */
                        'puoi'      ,   /* 148 */
                        'ciao'      ,   /* 149 */
                        'devi'      ,   /* 150 */
                        'ecco'      ,   /* 151 */
                        'qualcuno'  ,   /* 152 */
                        'dal'       ,   /* 153 */
                        'lavoro'    ,   /* 154 */
                        'sa'        ,   /* 155 */
                        'ai'        ,   /* 156 */
                        'vedere'    ,   /* 157 */
                        'ogni'      ,   /* 158 */
                        'ii'        ,   /* 159 */
                        'troppo'    ,   /* 160 */
                        'posto'     ,   /* 161 */
                        'cui'       ,   /* 162 */
                        'tanto'     ,   /* 163 */
                        'male'      ,   /* 164 */
                        'dai'       ,   /* 165 */
                        'ce'        ,   /* 166 */
                        'bisogno'   ,   /* 167 */
                        'signor'    ,   /* 168 */
                        'beh'       ,   /* 169 */
                        'perchè'    ,   /* 170 */
                        'vieni'     ,   /* 171 */
                        'alle'      ,   /* 172 */
                        'dalla'     ,   /* 173 */
                        'stata'     ,   /* 174 */
                        'tra'       ,   /* 175 */
                        'vai'       ,   /* 176 */
                        'ehi'       ,   /* 177 */
                        'miei'      ,   /* 178 */
                        'amico'     ,   /* 179 */
                        'dice'      ,   /* 180 */
                        'sarebbe'   ,   /* 181 */
                        'avete'     ,   /* 182 */
                        'altra'     ,   /* 183 */
                        'deve'      ,   /* 184 */
                        'sulla'     ,   /* 185 */
                        'qualche'   ,   /* 186 */
                        'sembra'    ,   /* 187 */
                        'gente'     ,   /* 188 */
                        'dobbiamo'  ,   /* 189 */
                        'modo'      ,   /* 190 */
                        'tre'       ,   /* 191 */
                        'momento'   ,   /* 192 */
                        'prego'     ,   /* 193 */
                        'parlare'   ,   /* 194 */
                        'mamma'     ,   /* 195 */
                        'guarda'    ,   /* 196 */
                        'signora'   ,   /* 197 */
                        'grande'    ,   /* 198 */
                        'lì'        ,   /* 199 */
                        'madre' );      /* 200 */
?>