<?php
/* Portuguese - 200 - https://en.wiktionary.org/wiki/Wiktionary:Frequency_lists/Portuguese_wordlist */
$aWords['pt'] = array ( 'que'       ,   /* 01  */
                        'não'       ,   /* 02  */
                        'de'        ,   /* 03  */
                        'um'        ,   /* 04  */
                        'para'      ,   /* 05  */
                        'eu'        ,   /* 06  */
                        'se'        ,   /* 07  */
                        'me'        ,   /* 08  */
                        'uma'       ,   /* 09  */
                        'está'      ,   /* 10  */
                        'com'       ,   /* 11  */
                        'do'        ,   /* 12  */
                        'por'       ,   /* 13  */
                        'te'        ,   /* 14  */
                        'os'        ,   /* 15  */
                        'bem'       ,   /* 16  */
                        'em'        ,   /* 17  */
                        'ele'       ,   /* 18  */
                        'isso'      ,   /* 19  */
                        'mas'       ,   /* 20  */
                        'da'        ,   /* 21  */
                        'como'      ,   /* 22  */
                        'no'        ,   /* 23  */
                        'sim'       ,   /* 24  */
                        'as'        ,   /* 25  */
                        'mais'      ,   /* 26  */
                        'na'        ,   /* 27  */
                        'meu'       ,   /* 28  */
                        'você'      ,   /* 29  */
                        'aqui'      ,   /* 30  */
                        'muito'     ,   /* 31  */
                        'foi'       ,   /* 32  */
                        'estou'     ,   /* 33  */
                        'vamos'     ,   /* 34  */
                        'ela'       ,   /* 35  */
                        'fazer'     ,   /* 36  */
                        'vai'       ,   /* 37  */
                        'isto'      ,   /* 38  */
                        'já'        ,   /* 39  */
                        'tem'       ,   /* 40  */
                        'só'        ,   /* 41  */
                        'minha'     ,   /* 42  */
                        'nos'       ,   /* 43  */
                        'ser'       ,   /* 44  */
                        'tudo'      ,   /* 45  */
                        'ao'        ,   /* 46  */
                        'tenho'     ,   /* 47  */
                        'vou'       ,   /* 48  */
                        'sei'       ,   /* 49  */
                        'agora'     ,   /* 50  */
                        'há'        ,   /* 51 */
                        'lá'        ,   /* 52 */
                        'tu'        ,   /* 53 */
                        'quando'    ,   /* 54 */
                        'porque'    ,   /* 55 */
                        'estás'     ,   /* 56 */
                        'quem'      ,   /* 57 */
                        'onde'      ,   /* 58 */
                        'nada'      ,   /* 59 */
                        'ter'       ,   /* 60 */
                        'então'     ,   /* 61 */
                        'dizer'     ,   /* 62 */
                        'lhe'       ,   /* 63 */
                        'seu'       ,   /* 64 */
                        'era'       ,   /* 65 */
                        'sou'       ,   /* 66 */
                        'ou'        ,   /* 67 */
                        'coisa'     ,   /* 68 */
                        'quero'     ,   /* 69 */
                        'são'       ,   /* 70 */
                        'sua'       ,   /* 71 */
                        'pode'      ,   /* 72 */
                        'nós'       ,   /* 73 */
                        'mesmo'     ,   /* 74 */
                        'ver'       ,   /* 75 */
                        'disse'     ,   /* 76 */
                        'eles'      ,   /* 77 */
                        'bom'       ,   /* 78 */
                        'estava'    ,   /* 79 */
                        'esta'      ,   /* 80 */
                        'todos'     ,   /* 81 */
                        'mim'       ,   /* 82 */
                        'posso'     ,   /* 83 */
                        'dos'       ,   /* 84 */
                        'lo'        ,   /* 85 */
                        'estão'     ,   /* 86 */
                        'temos'     ,   /* 87 */
                        'nunca'     ,   /* 88 */
                        'este'      ,   /* 89 */
                        'casa'      ,   /* 90 */
                        'até'       ,   /* 91 */
                        'assim'     ,   /* 92 */
                        'acho'      ,   /* 93 */
                        'quer'      ,   /* 94 */
                        'tens'      ,   /* 95 */
                        'tempo'     ,   /* 96 */
                        'ir'        ,   /* 97 */
                        'falar'     ,   /* 98 */
                        'quê'       ,   /* 99 */
                        'ainda'     ,   /* 100*/
                        'tua'       ,   /* 101 */
                        'teu'       ,   /* 102 */
                        'favor'     ,   /* 103 */
                        'pai'       ,   /* 104 */
                        'também'    ,   /* 105 */
                        'obrigado'  ,   /* 106 */
                        'vez'       ,   /* 107 */
                        'deus'      ,   /* 108 */
                        'certo'     ,   /* 109 */
                        'tão'       ,   /* 110 */
                        'sobre'     ,   /* 111 */
                        'melhor'    ,   /* 112 */
                        'noite'     ,   /* 113 */
                        'és'        ,   /* 114 */
                        'dia'       ,   /* 115 */
                        'estamos'   ,   /* 116 */
                        'talvez'    ,   /* 117 */
                        'nem'       ,   /* 118 */
                        'depois'    ,   /* 119 */
                        'sempre'    ,   /* 120 */
                        'sabe'      ,   /* 121 */
                        'mãe'       ,   /* 122 */
                        'vida'      ,   /* 123 */
                        'sem'       ,   /* 124 */
                        'alguém'    ,   /* 125 */
                        'olá'       ,   /* 126 */
                        'anos'      ,   /* 127 */
                        'sabes'     ,   /* 128 */
                        'ti'        ,   /* 129 */
                        'homem'     ,   /* 130 */
                        'dele'      ,   /* 131 */
                        'alguma'    ,   /* 132 */
                        'das'       ,   /* 133 */
                        'algo'      ,   /* 134 */
                        'parece'    ,   /* 135 */
                        'sr'        ,   /* 136 */
                        'tinha'     ,   /* 137 */
                        'senhor'    ,   /* 138 */
                        'boa'       ,   /* 139 */
                        'vais'      ,   /* 140 */
                        'coisas'    ,   /* 141 */
                        'estar'     ,   /* 142 */
                        'faz'       ,   /* 143 */
                        'queres'    ,   /* 144 */
                        'vocês'     ,   /* 145 */
                        'dois'      ,   /* 146 */
                        'ficar'     ,   /* 147 */
                        'pelo'      ,   /* 148 */
                        'preciso'   ,   /* 149 */
                        'aí'        ,   /* 150 */
                        'diz'       ,   /* 151 */
                        'claro'     ,   /* 152 */
                        'pessoas'   ,   /* 153 */
                        'essa'      ,   /* 154 */
                        'verdade'   ,   /* 155 */
                        'dar'       ,   /* 156 */
                        'esse'      ,   /* 157 */
                        'antes'     ,   /* 158 */
                        'ninguém'   ,   /* 159 */
                        'tipo'      ,   /* 160 */
                        'la'        ,   /* 161 */
                        'vão'       ,   /* 162 */
                        'trabalho'  ,   /* 163 */
                        'oh'        ,   /* 164 */
                        'grande'    ,   /* 165 */
                        'comigo'    ,   /* 166 */
                        'outra'     ,   /* 167 */
                        'apenas'    ,   /* 168 */
                        'espera'    ,   /* 169 */
                        'saber'     ,   /* 170 */
                        'vá'        ,   /* 171 */
                        'podes'     ,   /* 172 */
                        'pouco'     ,   /* 173 */
                        'dinheiro'  ,   /* 174 */
                        'qual'      ,   /* 175 */
                        'qualquer'  ,   /* 176 */
                        'pois'      ,   /* 177 */
                        'podemos'   ,   /* 178 */
                        'fora'      ,   /* 179 */
                        'pela'      ,   /* 180 */
                        'merda'     ,   /* 181 */
                        'deve'      ,   /* 182 */
                        'daqui'     ,   /* 183 */
                        'olha'      ,   /* 184 */
                        'cá'        ,   /* 185 */
                        'filho'     ,   /* 186 */
                        'disso'     ,   /* 187 */
                        'toda'      ,   /* 188 */
                        'hoje'      ,   /* 189 */
                        'mulher'    ,   /* 190 */
                        'meus'      ,   /* 191 */
                        'todo'      ,   /* 192 */
                        'nome'      ,   /* 193 */
                        'seja'      ,   /* 194 */
                        'num'       ,   /* 195 */
                        'desculpa'  ,   /* 196 */
                        'outro'     ,   /* 197 */
                        'nosso'     ,   /* 198 */
                        'nossa'     ,   /* 199 */
                        'sair' );       /* 200 */
?>