<?php
   /* Spanish - 200 - https://en.wiktionary.org/wiki/Wiktionary:Frequency_lists/Spanish1000 */
$aWords['es'] = array ( 'que'       ,   /* 01 */
                        'de'        ,   /* 02 */
                        'no'        ,   /* 03 */
                        'a'         ,   /* 04 */
                        'la'        ,   /* 05 */
                        'el'        ,   /* 06 */
                        'es'        ,   /* 07 */
                        'y'         ,   /* 08 */
                        'en'        ,   /* 09 */
                        'lo'        ,   /* 10 */
                        'un'        ,   /* 11 */
                        'por'       ,   /* 12 */
                        'qué'       ,   /* 13 */
                        'me'        ,   /* 14 */
                        'una'       ,   /* 15 */
                        'te'        ,   /* 16 */
                        'los'       ,   /* 17 */
                        'se'        ,   /* 18 */
                        'con'       ,   /* 19 */
                        'para'      ,   /* 20 */
                        'mi'        ,   /* 21 */
                        'está'      ,   /* 22 */
                        'si'        ,   /* 23 */
                        'bien'      ,   /* 24 */
                        'pero'      ,   /* 25 */
                        'yo'        ,   /* 26 */
                        'eso'       ,   /* 27 */
                        'las'       ,   /* 28 */
                        'sí'        ,   /* 29 */
                        'su'        ,   /* 30 */
                        'tu'        ,   /* 31 */
                        'aquí'      ,   /* 32 */
                        'del'       ,   /* 33 */
                        'al'        ,   /* 34 */
                        'como'      ,   /* 35 */
                        'le'        ,   /* 36 */
                        'más'       ,   /* 37 */
                        'esto'      ,   /* 38 */
                        'ya'        ,   /* 39 */
                        'todo'      ,   /* 40 */
                        'esta'      ,   /* 41 */
                        'vamos'     ,   /* 42 */
                        'muy'       ,   /* 43 */
                        'hay'       ,   /* 44 */
                        'ahora'     ,   /* 45 */
                        'algo'      ,   /* 46 */
                        'estoy'     ,   /* 47 */
                        'tengo'     ,   /* 48 */
                        'nos'       ,   /* 49 */
                        'tú'        ,   /* 50 */
                        'nada'      ,   /* 51 */
                        'cuando'    ,   /* 52 */
                        'ha'        ,   /* 53 */
                        'este'      ,   /* 54 */
                        'sé'        ,   /* 55 */
                        'estás'     ,   /* 56 */
                        'así'       ,   /* 57 */
                        'puedo'     ,   /* 58 */
                        'cómo'      ,   /* 59 */
                        'quiero'    ,   /* 60 */
                        'sólo'      ,   /* 61 */
                        'soy'       ,   /* 62 */
                        'tiene'     ,   /* 63 */
                        'gracias'   ,   /* 64 */
                        'o'         ,   /* 65 */
                        'él'        ,   /* 66 */
                        'bueno'     ,   /* 67 */
                        'fue'       ,   /* 68 */
                        'ser'       ,   /* 69 */
                        'hacer'     ,   /* 70 */
                        'son'       ,   /* 71 */
                        'todos'     ,   /* 72 */
                        'era'       ,   /* 73 */
                        'eres'      ,   /* 74 */
                        'vez'       ,   /* 75 */
                        'tienes'    ,   /* 76 */
                        'creo'      ,   /* 77 */
                        'ella'      ,   /* 78 */
                        'he'        ,   /* 79 */
                        'ese'       ,   /* 80 */
                        'voy'       ,   /* 81 */
                        'puede'     ,   /* 82 */
                        'sabes'     ,   /* 83 */
                        'hola'      ,   /* 84 */
                        'sus'       ,   /* 85 */
                        'porque'    ,   /* 86 */
                        'dios'      ,   /* 87 */
                        'quién'     ,   /* 88 */
                        'nunca'     ,   /* 89 */
                        'dónde'     ,   /* 90 */
                        'quieres'   ,   /* 91 */
                        'casa'      ,   /* 92 */
                        'favor'     ,   /* 93 */
                        'esa'       ,   /* 94 */
                        'dos'       ,   /* 95 */
                        'tan'       ,   /* 96 */
                        'señor'     ,   /* 97 */
                        'tiempo'    ,   /* 98 */
                        'verdad'    ,   /* 99 */
                        'estaba'    ,   /* 100 */
                        'mejor'     ,   /* 101 */
                        'están'     ,   /* 102 */
                        'va'        ,   /* 103 */
                        'hombre'    ,   /* 104 */
                        'usted'     ,   /* 105 */
                        'mucho'     ,   /* 106 */
                        'hace'      ,   /* 107 */
                        'entonces'  ,   /* 108 */
                        'siento'    ,   /* 109 */
                        'tenemos'   ,   /* 110 */
                        'puedes'    ,   /* 111 */
                        'ahí'       ,   /* 112 */
                        'ti'        ,   /* 113 */
                        'vida'      ,   /* 114 */
                        'ver'       ,   /* 115 */
                        'alguien'   ,   /* 116 */
                        'sr'        ,   /* 117 */
                        'hasta'     ,   /* 118 */
                        'sin'       ,   /* 119 */
                        'mí'        ,   /* 120 */
                        'solo'      ,   /* 121 */
                        'años'      ,   /* 122 */
                        'sobre'     ,   /* 123 */
                        'decir'     ,   /* 124 */
                        'uno'       ,   /* 125 */
                        'siempre'   ,   /* 126 */
                        'oh'        ,   /* 127 */
                        'ir'        ,   /* 128 */
                        'cosas'     ,   /* 129 */
                        'también'   ,   /* 130 */
                        'antes'     ,   /* 131 */
                        'has'       ,   /* 132 */
                        'ni'        ,   /* 133 */
                        'mis'       ,   /* 134 */
                        'día'       ,   /* 135 */
                        'estar'     ,   /* 136 */
                        'estamos'   ,   /* 137 */
                        'noche'     ,   /* 138 */
                        'nadie'     ,   /* 139 */
                        'otra'      ,   /* 140 */
                        'quiere'    ,   /* 141 */
                        'parece'    ,   /* 142 */
                        'nosotros'  ,   /* 143 */
                        'poco'      ,   /* 144 */
                        'padre'     ,   /* 145 */
                        'trabajo'   ,   /* 146 */
                        'gente'     ,   /* 147 */
                        'mira'      ,   /* 148 */
                        'vas'       ,   /* 149 */
                        'sea'       ,   /* 150 */
                        'les'       ,   /* 151 */
                        'donde'     ,   /* 152 */
                        'mismo'     ,   /* 153 */
                        'hecho'     ,   /* 154 */
                        'ellos'     ,   /* 155 */
                        'dijo'      ,   /* 156 */
                        'pasa'      ,   /* 157 */
                        'dinero'    ,   /* 158 */
                        'hijo'      ,   /* 159 */
                        'tal'       ,   /* 160 */
                        'otro'      ,   /* 161 */
                        'hablar'    ,   /* 162 */
                        'seguro'    ,   /* 163 */
                        'claro'     ,   /* 164 */
                        'estas'     ,   /* 165 */
                        'lugar'     ,   /* 166 */
                        'mundo'     ,   /* 167 */
                        'amigo'     ,   /* 168 */
                        'espera'    ,   /* 169 */
                        'mierda'    ,   /* 170 */
                        'han'       ,   /* 171 */
                        'tus'       ,   /* 172 */
                        'sabe'      ,   /* 173 */
                        'después'   ,   /* 174 */
                        'momento'   ,   /* 175 */
                        'desde'     ,   /* 176 */
                        'fuera'     ,   /* 177 */
                        'cosa'      ,   /* 178 */
                        'tipo'      ,   /* 179 */
                        'mañana'    ,   /* 180 */
                        'podemos'   ,   /* 181 */
                        'dije'      ,   /* 182 */
                        'gran'      ,   /* 183 */
                        'necesito'  ,   /* 184 */
                        'estado'    ,   /* 185 */
                        'podría'    ,   /* 186 */
                        'acuerdo'   ,   /* 187 */
                        'papá'      ,   /* 188 */
                        'tener'     ,   /* 189 */
                        'dice'      ,   /* 190 */
                        'mío'       ,   /* 191 */
                        'crees'     ,   /* 192 */
                        'buena'     ,   /* 193 */
                        'gusta'     ,   /* 194 */
                        'nuestro'   ,   /* 195 */
                        'nuevo'     ,   /* 196 */
                        'será'      ,   /* 197 */
                        'haciendo'  ,   /* 198 */
                        'días'      ,   /* 199 */
                        'nombre' );     /* 200 */
?>